title: BTech SY
description: Resources and reference materials for second-year BTech Computer Engineering, including assignments and notes.
theme: jekyll-theme-cayman
show_downloads: true
github: true
